package testCases;

import org.testng.Assert;
import org.testng.annotations.Test;

import PageObjects.HomePage;
import PageObjects.PracticePage;
import PageObjects.PracticeTestLogin;
import PageObjects.TestExceptionPage;
import testBase.BaseClass;

public class TC004_TestExceptionAdd extends BaseClass {

	@Test(groups = "Regression")
	public void Verify_add_favorite_food() {
		logger.info("***********Starting TC001_LogInSuccess ************");

		try {
			HomePage hp = new HomePage(driver);
			hp.clickPracticeMenu();
			logger.info("Clicked on Practice Menu");
			TestExceptionPage te = new TestExceptionPage(driver);
			te.clickEditButton();
			te.addFavouriteFood("burger");
			logger.info("Clicked on Test Login link");
			PracticeTestLogin ptl = new PracticeTestLogin(driver);
			ptl.setUserName(prop.getProperty("userName"));
			ptl.setUserPwd(prop.getProperty("pwd"));
			ptl.clickSubmit();
			logger.info("Entered username and pwd then clicked submit button");
			String loginmsg = ptl.getLoginConfirmation();

			if (loginmsg.equalsIgnoreCase("Congratulations student. You successfully logged in!")) {
				
				
				
			} else {
				logger.error("Test failed");
				logger.debug("Login validation failed");
				Assert.assertTrue(false);
			}

		} catch (Exception e) {

			Assert.fail();
			logger.debug("Exception: " + e.getMessage());
		}
		logger.info("***********Ending TC001_LogInSuccess ************");

	}
}
