<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Dell-Home-laptop" failures="1" tests="2" name="Login" time="33.92" errors="0" timestamp="2024-11-28T15:55:14 AEST">
  <testcase classname="testCases.TC002_LogInFail" name="Verify_Login_Fail" time="2.754">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC002_LogInFail.Verify_Login_Fail(TC002_LogInFail.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Verify_Login_Fail -->
  <testcase classname="testCases.TC004_TestException_TC2" name="Verify_add_favorite_food" time="16.633"/>
  <testcase classname="testCases.TC001_LogInSuccess" name="Veiry_Login_Success" time="0.0">
    <ignored/>
  </testcase> <!-- Veiry_Login_Success -->
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="0.0">
    <ignored/>
  </testcase> <!-- Verify_LoginByDataDriven -->
</testsuite> <!-- Login -->
