<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-Home-laptop" failures="1" tests="8" name="Login" time="87.431" errors="0" timestamp="2024-11-28T12:07:06 AEST">
  <testcase classname="testCases.TC001_LogInSuccess" name="Veiry_Login_Success" time="13.325">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC001_LogInSuccess.Veiry_Login_Success(TC001_LogInSuccess.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Veiry_Login_Success -->
  <testcase classname="testCases.TC002_LogInFail" name="Verify_Login_Fail" time="1.834"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="3.148"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="10.675"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="11.739"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="2.436"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="10.571"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="11.846"/>
</testsuite> <!-- Login -->
